---
server:
  type: simple
  applicationContextPath: /
  adminContextPath: /admin
  connector:
    type: http
    port: ${PORT:-8080}
  requestLog:
    appenders:
    - type: console
      filterFactories:
      - type: noise
        path: healthcheck

logging:
  level: ${ROOT_LOG_LEVEL:-INFO}
  loggers:
    # Enable errors from body processing
    io.dropwziard.jersey.jackson.JsonProcessingExceptionMapper: DEBUG

database:
  endpoints:
    write: ${WRITE_ENDPOINT}
    read: ${READ_ENDPOINT}
  port: ${DB_PORT}
  enableAwsSigner: ${ENABLE_AWS_SIGNING:-true}
  enableSsl: ${ENABLE_SSL:-true}

aws:
  ses:
    region: ${AWS_SES_REGION:-us-east-1}
    endpoint: ${AWS_SES_ENDPOINT:-null}

notifications:
  email:
    fromAddress: ${NOTIFICATION_FROM_EMAIL_ADDRESS:-noreply@zerobase.io}

siteTypeCategories:
  BUSINESS:
    - GROCERY
    - RESTAURANT
  FINANCIAL:
    - BANK
  HEALTH:
    - DOCTOR_OFFICE
    - HOSPITAL
    - PHARMACY

scannableTypes:
  - QR_CODE
