---
server:
  applicationConnectors:
  - type: http
    port: ${PORT:-9000}
allowedOrigins: '*'

logging:
  level: ${ROOT_LOG_LEVEL:-INFO}
  loggers:
    io.zerobase: DEBUG
    # Enable errors from body processing
    io.dropwizard.jersey.jackson.JsonProcessingExceptionMapper: DEBUG

database:
  endpoints:
    write: ${DB_HOST:-127.0.0.1}
  port: ${DB_PORT:-8182}

aws:
  ses:
    region: ${REGION:-us-east-1}
    endpoint: ${FAKE_SES_ENDPOINT:-http://127.0.0.1:4579}
  s3:
    region: ${REGION:-us-east-1}

baseQrCodeLink: http://127.0.0.1:8080/s/

notifications:
  staticResourcesBucket: ${STATIC_RESOURCES_BUCKET:-local-static-resources}
  email:
    fromAddress: ${NOTIFICATION_FROM_EMAIL_ADDRESS:-noreply@zerobase.io}

siteTypeCategories:
  BUSINESS:
  - GROCERY
  - RESTAURANT
  - OTHER
  FINANCIAL:
  - BANK
  - OTHER
  HEALTH:
  - DOCTOR_OFFICE
  - HOSPITAL
  - PHARMACY
  - OTHER
  OTHER:
  - OTHER

scannableTypes:
- QR_CODE
